### ISSUE TITLE
Package.json version update

### ISSUE THREAD

**Issue by heysailor** [felixfbecker/semantic-release-docker#17]
Thanks for a very handy plugin. One thing I'm missing is the update of package.json version.

The `@semantic-version/npm` plugin does this just before publishing to npm, for example. 

It's [discussed here](https://semantic-release.gitbooks.io/semantic-release/content/docs/support/FAQ.html#why-is-the-packagejsons-version-not-updated-in-my-repository) - I wonder if this could be integrated into `semantic-release-docker` so that images are internally aware of their semantic version.

**Comment by lucasfcosta** [comment]
+1 for this. That would be amazing.

**Comment by heysailor** [comment]
Let me know what you think. Have added a prepare plugin step that updates package.json, then runs a user-specified command to build the Docker image.

You have to build the image with the plugin so it includes the updated package.json.

Pushing to Docker is unchanged.

Kudos to [Pierre Vanduynslager](https://twitter.com/@pvdlg_) who wrote the package.json update code, which I've blatantly copied from [semantic-release/npm](https://github.com/semantic-release/npm).

**Comment by byCedric** [comment]
I like the idea very much too! But, I do have one question. The nature of semantic release is to add various plugins to your release process. I'm not sure why we can't simply add `@semantic-release/npm` as extra prepare (and verify conditions) step. Keeping this separated will benefit maintainability since the NPM package is maintained by the semantic release authors them selfs.

**Comment by felixfbecker** [comment]
Why can't you just specify `@semantic-release/npm` as the `prepare` step? Not every Docker image will have a package.json, they might be written in completely different languages - so I am reluctant to add support for things that are package-manager specific (i.e. have nothing to do with Docker)

**Comment by byCedric** [comment]
@felixfbecker I get that, and that's definitely a good thing. I was more referring the fact that this docker plugin is _one of multiple_ plugins for a project. 

The initial question was the update of a package file. I don't believe in recreating the `@semantic-release/npm` plugin, within the docker plugin. You can add it as extra step in your project's release config. And, like you said, if you don't use it you can also _not-include_ it in your project's config 🙂

**Comment by heysailor** [comment]
The trouble with the npm plugin was that it doesn't leave the updated
version in package.json.

**Comment by felixfbecker** [comment]
@heysailor could you elaborate? The `prepare` step of the npm plugin should update it, so which step removes it?

**Comment by OskarLebuda** [comment]
Hi. Can someone tell me how to update the `package.json` which is inside of the builded image? Look. I build the image before the `semantic-release` runs, so I have no idea how to update the version of package in `semantic-release-docker`. Here is my example:
.releaserc
```
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    ["@semantic-release/git", {
      "assets": ["dist/**/*.{js,css}", "docs", "package.json"],
      "message": "chore(release): ${nextRelease.version}"
    }],
    "semantic-release-docker"
  ],
  "npmPublish": false,
  "publish": [
    {
      "path": "semantic-release-docker",
      "name": "myname/my-repo"
    }
  ]
}
```

and my `travis-ci` script:
```
...
jobs:
  include:
    - stage: release
      language: node_js
      node_js: 11.13.0
      script:
        - docker build -t myname/my-repo
        - npm run semantic-release
``` 
so the question is how can i update the version whitch is actually inside the new builded image ;(

**Comment by felixfbecker** [comment]
You need to build the image as part of semantic-release (instead of before). Example:

https://github.com/felixfbecker/php-language-server/blob/9dc16565922ae1fcf18a69b15b3cd15152ea21e6/package.json#L12-L30

**Comment by OskarLebuda** [comment]
Ok but when I use your example my `semantic-release-git` doesn't work. I use it like this:

```json
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    [
      "@semantic-release/git",
      {
        "assets": ["dist/**/*.{js,css}", "docs", "package.json"],
        "message": "chore(release): ${nextRelease.version}"
      }
    ],
    "semantic-release-docker"
  ],
  "npmPublish": false,
  "prepare": [
    {
      "path": "@semantic-release/exec",
      "cmd": "docker build -t semis/kodilla-google-calendar ."
    }
  ],
  "publish": [
    {
      "path": "semantic-release-docker",
      "name": "semis/kodilla-google-calendar"
    }
  ]
}
```
have you any ideas? @felixfbecker

**Comment by felixfbecker** [comment]
"doesn't work" is very unspecific, are there errors or logs? Any other info? 

One thing that I see is that you're mixing the `plugins` config with configuring specific steps. You probably want to specify the steps manually and not use `plugins`, else I don't know how if it would run them in the right order. But this could also be unrelated.

**Comment by OskarLebuda** [comment]
ok I've fix it ;) Here is the solution

```json
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm",
    [
      "@semantic-release/git",
      {
        "assets": ["dist/**/*.{js,css}", "docs", "package.json"],
        "message": "chore(release): ${nextRelease.version}"
      }
    ],
    [
      "@semantic-release/exec",
      {
        "prepareCmd": "docker build -t semis/kodilla-google-calendar ."
      }
    ],
    "semantic-release-docker"
  ],
  "npmPublish": false,
  "publish": [
    {
      "path": "semantic-release-docker",
      "name": "semis/kodilla-google-calendar"
    }
  ]
}
```

**Comment by felixfbecker** [comment]
Great to hear you could make it work.

I am going to close this issue since it seems to work fine and there was no response from the original author.
